### ISSUE TITLE
opensky.history returns None

### ISSUE THREAD

**Issue by damsabella** [xoolive/traffic#171] opened 2021-12-11 17:32 UTC
The function opensky.history returns None and it's very difficult to debug.

If I would like to pull historical takeoff/landing data from LAX, I use the following code.

```python
from traffic.data import opensky

opensky.history('2020-01-01', '2020-01-02', cached=False, departure_airport='LAX')    # returns None
```

The function correctly sends all 24 hourly requests as expected, however the function output is None. Can anyone explain this?

I use:
- Python 3.9.7
- Traffic==2.6.6
- Ubuntu 20.04

I'm keen to find a solution as quickly as possible, so please let me know if you have any ideas.

**Comment by xoolive** [comment] 2021-12-11 18:10
Airports in opensky are encoded with their ICAO identifier. Replace LAX by KLAX.

**Comment by xoolive** [comment] 2021-12-12 15:31
I'll close the issue, feel free to reopen if need be.
For general assistance, please prefer https://gitter.im/xoolive/traffic

**Closed by xoolive** 2021-12-12 15:31 UTC
Labels: question

**Comment by damsabella** [comment] 2021-12-12 21:42
Thanks for the help, perhaps this could be updated in the documentation, or the function throws an error if an invalid airport code is provided?

**Comment by xoolive** [comment] 2021-12-12 21:47
Actually that's already in the documentation:
https://traffic-viz.github.io/opensky_impala.html#historical-traffic-data

How would you rephrase it? (PR welcome! 😄 )

<img width="700" alt="Capture d’écran 2021-12-12 à 22 44 11" src="https://user-images.githubusercontent.com/1360812/145730757-e4f4795f-08c0-446d-9a13-881fd9bf48e3.png">

**Comment by damsabella** [comment] 2021-12-13 14:47
The issue persists even using the ICAO identifier of the airport. I don't want to create a new issue but there is a problem with running long `opensky.history(start, stop, departure_airport || arrival_airport)` jobs. I'm trying to pull months of data which takes a long time to run.

The progress bar will often freeze, requiring the script to be restarted (potentially related, but also another issue)

I still encounter the same issue that `opensky.history` returns `None`. This is very frustrating given the job takes so long to execute.

**Comment by xoolive** [comment] 2021-12-13 15:06
If things freeze, it's certainly a connection issue.
For this granularity, I would download data day per day (and save the results each time).

**Comment by wtroisey** [comment] 2022-02-15 09:50
Hi, 

I'm encountering the same issue as above but none of the solutions above are working for me.

I'm trying to get a list of all departures from LAX between two dates in Jan 2017.

traffic version 2.6.6

```python
from traffic.data import opensky

flights = opensky.history(
    start='some datetime',
    stop='some datetime',
    departure_airport='KLAX',
    arrival_airport=None,
    icao24=None,
    cached=False
)

print(flights) # > None
```

Please can you advise where I'm going wrong?

Regards, 
Will

**Comment by xoolive** [comment] 2022-02-15 10:14
I cannot reproduce the issue:

```
from traffic.data import opensky

flights = opensky.history(
    start='2022-01-01 00:00',
    stop='2022-01-01 01:00',
    departure_airport='KLAX',
    arrival_airport=None,
    icao24=None,
    # cached=False
)
flights
```

![image](https://user-images.githubusercontent.com/1360812/154040810-e702124e-45b7-42b1-9774-f0af1fb6941d.png)

If data is empty on your side, it may not be in the database anymore. Please provide the timestamps you requested if you need further assistance.

**Comment by wtroisey** [comment] 2022-02-15 11:59
Are you able to reproduce the issue in January 2017 for Bahrain airport, `OBBI`?

**Comment by xoolive** [comment] 2022-02-15 16:31
If it returns None that's because the database is empty for those dates/flight table
