### ISSUE TITLE
nm_airspaces not working as expected

### ISSUE THREAD

**Issue by jaimebw** [xoolive/traffic#95] opened 2020-08-06 11:18 UTC
Hello Mr. Olive,
Im having an issue using nm_airspaces. I have followed all the instructions in [here](https://traffic-viz.github.io/airac_usage.html) and I have the EUROCONTROL files, but when I tried to load them, they dont work.  
This is what Im doing:
``` python
from traffic.data import nm_airspaces
nm_airspaces['LECMBLU']   
```  
And the error I get is: 
```
ValueError: not enough values to unpack (expected at least 2, got 1)
```
I have followed all the instructions, the files are referenced in the config_file as said in the documentation, but Im unable to get this working. Do you know why this is happening? I think it might be an issue with the EUROCONTROL files.  
My next attempt will be to create my own geometric object, and try to use it with the Impala Shell.  
Thank you in advance
PS: Your library is great! It is helping me a lot with my BSc dissertation.

**Comment by jaimebw** [comment] 2020-08-07 15:39
I finally was able to correct this issue by editing the file by myself. I opened the .spc file and in the first line was written:
``` 111 ``` 
By deleting this line and rerunning the cell, it finally worked.

**Comment by xoolive** [comment] 2020-08-09 14:49
Thank you for the feedback. Let me reopen this, you shouldn't have to edit any source file yourself. I will look for a workaround. Can you confirm the name of the file you had to edit? (with the AIRAC cycle so I can go get the same one)

**Comment by jaimebw** [comment] 2020-08-10 14:17
If you want, I can send them to you. I am not sure if those files contain the whole AIRAC cycle, they might only contain spanish sector. I think the cycle is the 1811.

**Comment by xoolive** [comment] 2020-08-11 13:01
Thank you I will try with these files if I can still download them, but probably not before September...

**Comment by xoolive** [comment] 2020-09-08 14:40
It looks like you had an issue in your original file which may have been corrupted, I am not able to reproduce the issue on my side. Closing for now...

**Closed by xoolive** 2020-09-08 14:40 UTC
Labels: bug, good first issue

**Comment by jaimebw** [comment] 2020-10-05 10:14
I found out what was the issue. The data I was given wasn't download directly from Eurocontrol, it was obtained through NEST. Therefore, the info is previously formatted by the program, but changing those number in the ```.spc```  after exporting the file, makes it work just fine.

**Comment by xoolive** [comment] 2020-10-05 11:52
ok thanks for the update
