### ISSUE TITLE
Airports data is currently empty

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#164] opened 2021-11-01 21:04 UTC
Due to a problem at their end, the `ourairports` database provided at: https://ourairports.com/data/airports.csv
Is currently empty, with no airport data provided. This means that the `airports` functions in traffic simply return `None` for any airport.

In future, it'd be great to have some kind of fallback or alternative so that users can continue with, for example, an old version of the database if such problems occur.

**Comment by xoolive** [comment] 2021-11-01 21:17
Thanks, will do!

**Comment by xoolive** [comment] 2021-11-01 22:17
Related issue: URL change for https://junzis.com/adb/download/aircraft_db.zip

**Comment by robhawkes** [comment] 2021-11-02 23:58
Ah this sounds like what I've been hitting the past couple days.

Trying to run the following in a notebook:
```python
from traffic.data.samples import belevingsvlucht
belevingsvlucht
```

Results in the following errors, though the image of the flight does appear:
```python
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
/opt/conda/lib/python3.9/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/lib/python3.9/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/opt/conda/lib/python3.9/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/opt/conda/lib/python3.9/site-packages/traffic/core/flight.py in __repr__(self)
    308     def __repr__(self) -> str:
    309         output = f"Flight {self.title}"
--> 310         output += f"\naircraft: {self.aircraft}"
    311         if self.origin is not None:
    312             output += f"\norigin: {self.origin} ({self.start})"

/opt/conda/lib/python3.9/site-packages/traffic/core/flight.py in aircraft(self)
    812 
    813         res = str(self.icao24)
--> 814         ac = aircraft.get_unique(res)
    815 
    816         if ac is None:

/opt/conda/lib/python3.9/site-packages/traffic/data/basic/aircraft.py in get_unique(self, name)
    236 
    237     def get_unique(self, name: str) -> Optional[Dict[str, str]]:
--> 238         df = self[name]
    239 
    240         if df.shape[0] == 0:

/opt/conda/lib/python3.9/site-packages/traffic/data/basic/aircraft.py in __getitem__(self, name)
    228 
    229         if isinstance(name, str):
--> 230             df = self.data.query(
    231                 "icao24 == @name.lower() or registration == @name.upper()"
    232             )

/opt/conda/lib/python3.9/site-packages/traffic/data/basic/aircraft.py in data(self)
    211 
    212         if not (self.cache_dir / "opensky_db.pkl").exists():
--> 213             return self.junzis_db
    214 
    215         self._merged = self.junzis_db.merge(

/opt/conda/lib/python3.9/site-packages/traffic/data/basic/aircraft.py in junzis_db(self)
    143         if self._junzis is None:
    144             if not (self.cache_dir / "junzis_db.pkl").exists():
--> 145                 self.download_junzis()
    146             else:
    147                 logging.info("Loading @junzis aircraft database")

/opt/conda/lib/python3.9/site-packages/traffic/data/basic/aircraft.py in download_junzis(self)
    117 
    118         f = session.get("https://junzisun.com/adb/download")
--> 119         with zipfile.ZipFile(io.BytesIO(f.content)) as zfile:
    120             with zfile.open("aircraft_db.csv", "r") as dbfile:
    121                 self._junzis = (

/opt/conda/lib/python3.9/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1255         try:
   1256             if mode == 'r':
-> 1257                 self._RealGetContents()
   1258             elif mode in ('w', 'x'):
   1259                 # set the modified flag so central directory gets written

/opt/conda/lib/python3.9/zipfile.py in _RealGetContents(self)
   1322             raise BadZipFile("File is not a zip file")
   1323         if not endrec:
-> 1324             raise BadZipFile("File is not a zip file")
   1325         if self.debug > 1:
   1326             print(endrec)

BadZipFile: File is not a zip file
```

**Comment by xoolive** [comment] 2021-11-03 16:03
@simonrp84 did you by any chance keep the "empty" file when you hit on it?
@robhawkes v2.6.6 should be on pypi tonight, maybe on conda tomorrow morning

**Comment by shreyasmg** [comment] 2021-11-03 16:59
Hi @xoolive, I am also facing the same issue as @simonrp84. The 'airports' dataframe always returns empty, hence not able to use airport 'intersects' functionality. I hope the issue is resolved soon. Currently using traffic version 2.6.5.

**Comment by xoolive** [comment] 2021-11-03 17:03
Hi @shreyasmg, 

First update to v2.6.6 with `pip install -U traffic`.

Then try to force a new download of the airports:
```python
from traffic.data import airports

airports.download_airports()
```

**Comment by simonrp84** [comment] 2021-11-03 20:30
@simonrp84 Sorry, I deleted it.
But I remember that the file contained column headings and nothing else - no data at all.

**Comment by xoolive** [comment] 2021-11-03 20:38
ok this will help, thanks!

**Comment by xoolive** [comment] 2022-05-19 09:16
This seems to have been fixed in a previous commit, reopen if needed

**Closed by xoolive** 2022-05-19 09:16 UTC
Labels: bug
