### ISSUE TITLE
Runway Guess

### ISSUE THREAD

**Issue by EmpAk** [xoolive/traffic#53] opened 2019-11-26 16:53 UTC
I have been playing around with the airport and runway guesses. For the landing runway guess, an error is generated for the selection of the last 10 minutes:

_Error from pandas:_

>   File "C:\Users\olsc\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\computation\ops.py", line 426, in convert_values
>     if v.tz is not None:

AttributeError: 'NaTType' object has no attribute 'tz'

_Triggered by:_

> File "C:/EmpaDaten/Idealisierte_Spuren_aus_Radar/opensky_adsb/main_opensky_zrh18.py", line 79, in <module>
>     o=flight.guess_landing_runway()
> 
>   File "C:\Users\olsc\AppData\Local\Continuum\anaconda3\lib\site-packages\traffic\core\flight.py", line 1054, in guess_landing_runway
>     .last(minutes=10)
> 
>   File "C:\Users\olsc\AppData\Local\Continuum\anaconda3\lib\site-packages\traffic\core\flight.py", line 558, in last
>     return self.__class__(self.data.query("timestamp > @bound"))

**Comment by xoolive** [comment] 2019-11-26 16:58
Which flight are you playing with? It would be easier to assist you if you provide a way to reproduce the error.

According to the error message, it seems there is an invalid timestamp. Maybe you can try the guessing on `flight.query("timestamp == timestamp")` (which means "timestamp different from NaT") ?

On a side note, this (way too complex) implementation has been removed very few commits ago. I plan to add a new implementation asap.

**Comment by EmpAk** [comment] 2019-11-26 17:05
This example gives the error:

```
#
data_raw = opensky.history(
    "2018-01-21 12:00",
    "2018-01-21 15:00",
    bounds=(
        7.99182, 47.09367, #sw
        9.24188, 47.83655 #ne
    ),
)
    
#
flight_interest=[]
for flight in data_raw:
    curr_id=flight.assign_id()
    fz_typ=curr_id.typecode
    if fz_typ=='A320' and flight.min("altitude") < 2000: #in feet
        flight_interest.append(flight)
        o=flight.guess_landing_runway()
```

BTW, this is not that important for me - I can probably get a decent runway estimate myself quite quickly. I just wanted to report the issue.

**Comment by xoolive** [comment] 2019-11-26 17:10
Thank you I will have a look at this issue and keep you posted (also about the new runway estimation when it's online!)

**Comment by xoolive** [comment] 2019-11-27 08:20
I just had a look. The thing is that the method which has now been removed was not robust enough to raise an error when the trajectory was not actually a landing trajectory...

In the case of a take-off for instance, since the method selected only the part of the trajectory where the vertical_rate is negative, the resulting dataframe is empty and you cannot apply `.last(minutes=10)`.

Since the implementation was not that great anyway, it has been removed recently. I will keep in mind the robustness concern for the future implementation.

Closing the issue for now.

**Closed by xoolive** 2019-11-27 08:20 UTC
