### ISSUE TITLE
problem plotting traffic data (dtypes timedelta64 vs float64)

### ISSUE THREAD

**Issue by StephanSchiffel** [xoolive/traffic#119] opened 2021-03-09 12:11 UTC
I'm using the following code to try and plot traffic from the state vector data than can be downloaded from OpenSky (https://opensky-network.org/data/datasets#d1)

```python
from traffic.core import Traffic
import matplotlib.pyplot as plt

t = Traffic.from_file("data/states_2021-03-08-00.csv")

with plt.style.context("traffic"):
    ax = plt.gca()
    t.plot(ax)
    plt.show()
```
The code gives me the following error:
```
Traceback (most recent call last):
  ...
TypeError: The DTypes <class 'numpy.dtype[timedelta64]'> and <class 'numpy.dtype[float64]'> do not have a common DType. For example they cannot be stored in a single array unless the dtype is `object`.
```

Am I using the right way of doing this?

**Comment by xoolive** [comment] 2021-03-09 20:26
The issue is that the `timestamp` column needs to be of type `timestamp`.
It should work with the following workaround:

```python
Traffic.from_file(...).assign(
    timestamp=lambda df: pd.to_datetime(
        df.timestamp,
        unit="s",
    ).dt.tz_localize("utc")
)
```

**Comment by xoolive** [comment] 2021-03-16 20:42
I will close the issue, feel free to reopen is the problem persists

**Closed by xoolive** 2021-03-16 20:42 UTC
